// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import HeaderComponent from "./components/common/header/header-component";
import Footer from "./components/common/footer";
import MsalProviderWrapper from "../auth/MsalProviderWrapper";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MsalProviderWrapper>
          <HeaderComponent />
          <main className="content">{children}</main>
          <Footer />
        </MsalProviderWrapper>
      </body>
    </html>
  );
}